### ISSUE TITLE
Can not run getting started sample on `ImportError: dlopen(...): symbol not found in flat namespace '_kCFStreamPropertySocketNativeHandle'`

### ISSUE THREAD

**Issue by tommarulak-playinc** [aws-samples/pyflink-getting-started#22]
Hi there, not sure where to find help with my issue. Hopefully anyone here know what I am missing. I followed the instruction on the  [getting started page](https://github.com/aws-samples/pyflink-getting-started), I make sure I matched the pyflink (1.15.2) and the JVM version (v11). But when I run the main file, it fails on the `table_env = TableEnvironment.create(env_settings)`.

```
Traceback (most recent call last):
  File "/Users/sitorush/Sites/kinesis-analytics/main.py", line 18, in <module>
    table_env = TableEnvironment.create(env_settings)
  File "/Users/sitorush/miniconda3/envs/kinesis-flink/lib/python3.8/site-packages/pyflink/table/table_environment.py", line 113, in create
    return TableEnvironment(j_tenv)
  File "/Users/sitorush/miniconda3/envs/kinesis-flink/lib/python3.8/site-packages/pyflink/table/table_environment.py", line 98, in __init__
    self._open()
  File "/Users/sitorush/miniconda3/envs/kinesis-flink/lib/python3.8/site-packages/pyflink/table/table_environment.py", line 1637, in _open
    startup_loopback_server()
  File "/Users/sitorush/miniconda3/envs/kinesis-flink/lib/python3.8/site-packages/pyflink/table/table_environment.py", line 1628, in startup_loopback_server
    from pyflink.fn_execution.beam.beam_worker_pool_service import \
  File "/Users/sitorush/miniconda3/envs/kinesis-flink/lib/python3.8/site-packages/pyflink/fn_execution/beam/beam_worker_pool_service.py", line 26, in <module>
    import grpc
  File "/Users/sitorush/miniconda3/envs/kinesis-flink/lib/python3.8/site-packages/grpc/__init__.py", line 22, in <module>
    from grpc import _compression
  File "/Users/sitorush/miniconda3/envs/kinesis-flink/lib/python3.8/site-packages/grpc/_compression.py", line 20, in <module>
    from grpc._cython import cygrpc
ImportError: dlopen(/Users/sitorush/miniconda3/envs/kinesis-flink/lib/python3.8/site-packages/grpc/_cython/cygrpc.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace '_kCFStreamPropertySocketNativeHandle'

Process finished with exit code 1
```

Does anyone what is missing here? Thanks in advance

**Comment by jeremyber-aws** [comment]
We have seen issues with customers running on Apple M1 / Silicon Macs. Please follow [this](https://github.com/aws-samples/amazon-managed-service-for-apache-flink-examples/tree/main/python/LocalDevelopmentOnAppleSilicon) guide for additional help getting this one to work.
