### ISSUE TITLE
GettingStarted doesn't work, throws ClassNotFoundException

### ISSUE THREAD

**Issue by tlagore** [aws-samples/pyflink-getting-started#4]
Using Visual Studio Code,

launch.json:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "justMyCode": true,
            "env": {
                "IS_LOCAL": "true"
            }
        }
    ]
}
```

application_properties.json
```
[
  {
  "PropertyGroupId": "kinesis.analytics.flink.run.options",
  "PropertyMap": {
    "python": "GettingStarted/getting-started.py",
    "jarfile": "GettingStarted/lib/flink-sql-connector-kinesis_2.12-1.13.2"
   }
  },
  {
    "PropertyGroupId": "consumer.config.0",
    "PropertyMap": {
      "input.stream.name": "input-stream",
      "flink.stream.initpos": "LATEST",
      "aws.region": "us-west-2"
    }
  },
  {
    "PropertyGroupId": "producer.config.0",
    "PropertyMap": {
      "output.stream.name": "output-stream",
      "shard.count": "1",
      "aws.region": "us-west-2"
    }
  }
]
```

Using flink-connector-kinesis_2.12-1.13.2.jar from mvnrepository: https://mvnrepository.com/artifact/org.apache.flink/flink-connector-kinesis_2.12/1.13.2

exception thrown:
```
Exception has occurred: Py4JJavaError
An error occurred while calling o4.executeSql.
: org.apache.flink.table.api.ValidationException: Unable to create a source for reading table 'default_catalog.default_database.input_table'.

Table options are:

'aws.region'='us-west-2'
'connector'='kinesis'
'format'='json'
'json.timestamp-format.standard'='ISO-8601'
'scan.stream.initpos'='LATEST'
'sink.partitioner-field-delimiter'=';'
'sink.producer.collection-max-count'='100'
'stream'='input-stream'
	at org.apache.flink.table.factories.FactoryUtil.createTableSource(FactoryUtil.java:137)
	at org.apache.flink.table.planner.plan.schema.CatalogSourceTable.createDynamicTableSource(CatalogSourceTable.java:116)
	at org.apache.flink.table.planner.plan.schema.CatalogSourceTable.toRel(CatalogSourceTable.java:82)
	at org.apache.calcite.sql2rel.SqlToRelConverter.toRel(SqlToRelConverter.java:3585)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertIdentifier(SqlToRelConverter.java:2507)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertFrom(SqlToRelConverter.java:2144)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertFrom(SqlToRelConverter.java:2093)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertFrom(SqlToRelConverter.java:2050)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertSelectImpl(SqlToRelConverter.java:663)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertSelect(SqlToRelConverter.java:644)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertQueryRecursive(SqlToRelConverter.java:3438)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertQuery(SqlToRelConverter.java:570)
	at org.apache.flink.table.planner.calcite.FlinkPlannerImpl.org$apache$flink$table$planner$calcite$FlinkPlannerImpl$$rel(FlinkPlannerImpl.scala:169)
	at org.apache.flink.table.planner.calcite.FlinkPlannerImpl.rel(FlinkPlannerImpl.scala:161)
	at org.apache.flink.table.planner.operations.SqlToOperationConverter.toQueryOperation(SqlToOperationConverter.java:989)
	at org.apache.flink.table.planner.operations.SqlToOperationConverter.convertSqlQuery(SqlToOperationConverter.java:958)
	at org.apache.flink.table.planner.operations.SqlToOperationConverter.convert(SqlToOperationConverter.java:283)
	at org.apache.flink.table.planner.operations.SqlToOperationConverter.convertSqlInsert(SqlToOperationConverter.java:603)
	at org.apache.flink.table.planner.operations.SqlToOperationConverter.convert(SqlToOperationConverter.java:272)
	at org.apache.flink.table.planner.delegation.ParserImpl.parse(ParserImpl.java:101)
	at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeSql(TableEnvironmentImpl.java:724)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.flink.api.python.shaded.py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at org.apache.flink.api.python.shaded.py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at org.apache.flink.api.python.shaded.py4j.Gateway.invoke(Gateway.java:282)
	at org.apache.flink.api.python.shaded.py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at org.apache.flink.api.python.shaded.py4j.commands.CallCommand.execute(CallCommand.java:79)
	at org.apache.flink.api.python.shaded.py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/deser/BeanDeserializerModifier
	at org.apache.flink.streaming.connectors.kinesis.util.KinesisConfigUtil.validateAwsConfiguration(KinesisConfigUtil.java:552)
	at org.apache.flink.streaming.connectors.kinesis.util.KinesisConfigUtil.validateConsumerConfiguration(KinesisConfigUtil.java:96)
	at org.apache.flink.streaming.connectors.kinesis.table.KinesisDynamicTableFactory.validateConsumerProperties(KinesisDynamicTableFactory.java:153)
	at org.apache.flink.streaming.connectors.kinesis.table.KinesisDynamicTableFactory.createDynamicTableSource(KinesisDynamicTableFactory.java:75)
	at org.apache.flink.table.factories.FactoryUtil.createTableSource(FactoryUtil.java:134)
	... 31 more
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.deser.BeanDeserializerModifier
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 36 more
  File "/home/tyrone/repos/aws/pyflink-getting-started/pyflink-examples/GettingStarted/getting-started.py", line 151, in main
    table_result = table_env.execute_sql("INSERT INTO {0} SELECT * FROM {1}"
  File "/home/tyrone/repos/aws/pyflink-getting-started/pyflink-examples/GettingStarted/getting-started.py", line 162, in <module>
    main()
```

**Comment by jeremyber-aws** [comment]
Hi @tlagore can you please follow steps described in [this video](https://www.youtube.com/watch?v=00JgwB5vJps) and let me know if this works for you? This looks to me like a version mismatch version, but the working example in the video will identify any steps that may have been overlooked.

**Comment by jeremyber-aws** [comment]
Closing issue based on no response. Can reopen if necessary.
